# Generated by Django 4.1.7 on 2023-04-25 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=200)),
                ('productdescription', models.CharField(default='', max_length=300)),
                ('productimages', models.ImageField(blank=True, upload_to='api_app/img')),
                ('productThumbnail', models.ImageField(blank=True, upload_to='api_app/img')),
                ('productprice', models.IntegerField(blank=True)),
                ('productdiscountPercentage', models.IntegerField(blank=True)),
                ('productdiscountPrice', models.IntegerField(blank=True)),
                ('productfinalPrice', models.IntegerField(blank=True, null=True)),
                ('gsttax', models.IntegerField(blank=True)),
                ('productqty', models.IntegerField(blank=True)),
                ('productmetaTitle', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='True', max_length=20)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
