# Generated by Django 4.1.7 on 2023-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='userid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
