# Generated by Django 4.1.7 on 2023-04-26 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_product_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDescription', models.CharField(default='', max_length=500)),
                ('reviewTitle', models.CharField(default='', max_length=200)),
                ('reviewRating', models.IntegerField()),
                ('reviewImage', models.ImageField(default='', upload_to='api_app/img')),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
