# Generated by Django 4.1.7 on 2023-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_product_productreview_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
