# Generated by Django 4.1.7 on 2023-04-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product',
            new_name='product_name',
        ),
    ]
