# Generated by Django 4.1.7 on 2023-04-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_product_usercart_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='product_name',
            new_name='product',
        ),
    ]
